import { useState } from "react";
import { Link } from "react-router-dom";
import { CalendarDays, CheckCircle2, Clock, DollarSign, Download, FileText, HeartPulse, Plus, Search, Star, Stethoscope, Upload, Users } from "lucide-react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Pie, PieChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import toast from "react-hot-toast";
import { appointments as seedAppointments, doctors, records, prescriptions, analytics, departments, reviews } from "../../data/mockData";
import { useAppStore } from "../../store/appStore";
import { Card, PageHeader, StatCard, StatusBadge } from "../../components/ui";
import { Appointment } from "../../types";

export function PatientDashboard(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Patient Dashboard" text="Manage appointments, prescriptions, records, payments, and follow-up reminders." action={<Link className="btn-primary" to="/patient/book">Book Appointment</Link>}/><div className="grid gap-5 md:grid-cols-5"><StatCard label="Upcoming" value={String(appts.filter(a=>a.status==="Confirmed").length)} icon={<CalendarDays/>}/><StatCard label="Completed" value="8" icon={<CheckCircle2/>}/><StatCard label="Prescriptions" value={String(prescriptions.length)} icon={<FileText/>}/><StatCard label="Records" value={String(records.length)} icon={<Upload/>}/><StatCard label="Pending Payments" value="$35" icon={<DollarSign/>}/></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><AppointmentList title="Upcoming appointments" data={appts.slice(0,4)}/><LearningChart title="Visits by month"/></div></>}
export function BookAppointment(){const add=useAppStore(s=>s.addAppointment); const [doctor,setDoctor]=useState(doctors[0]); return <><PageHeader title="Book Appointment" text="Select a doctor, slot, consultation type, and patient information."/><div className="grid gap-8 lg:grid-cols-[1fr_380px]"><Card className="p-6"><h2 className="text-2xl font-black">Appointment Details</h2><div className="mt-5 grid gap-4 md:grid-cols-2"><select className="input" onChange={e=>setDoctor(doctors.find(d=>d.id===e.target.value)||doctors[0])}>{doctors.map(d=><option value={d.id} key={d.id}>{d.name} - {d.department}</option>)}</select><input className="input" type="date" defaultValue="2026-05-22"/><select className="input"><option>In-person</option><option>Video</option><option>Phone</option><option>Follow-up</option></select><select className="input">{doctor.slots.map(s=><option key={s}>{s}</option>)}</select><input className="input" placeholder="Patient name" defaultValue="Nasir Uddin Khan"/><input className="input" placeholder="Phone" defaultValue="+8801711111111"/><select className="input"><option>Male</option><option>Female</option><option>Other</option></select><input className="input" placeholder="Age" defaultValue="28"/></div><textarea className="input mt-4 h-32" placeholder="Symptoms / reason for visit" defaultValue="Regular consultation and follow-up check."/><button onClick={()=>{add({id:`APT-${Date.now()}`,patientName:"Nasir Uddin Khan",patientEmail:"patient@medicare.com",doctorId:doctor.id,doctorName:doctor.name,department:doctor.department,date:"2026-05-22",time:doctor.slots[0],type:"In-person",symptoms:"Regular consultation",fee:doctor.fee,status:"Pending",paymentStatus:"Unpaid"});toast.success("Appointment booked")}} className="btn-primary mt-5">Confirm Booking</button></Card><Card className="p-6"><img className="h-48 w-full rounded-3xl object-cover" src={doctor.image}/><h3 className="mt-4 text-xl font-black">{doctor.name}</h3><p className="text-slate-500">{doctor.specialization}</p><p className="mt-2 font-bold text-brand-600">${doctor.fee} consultation fee</p><h4 className="mt-5 font-black">Available slots</h4><div className="mt-2 flex flex-wrap gap-2">{doctor.slots.map(s=><span className="badge bg-slate-100 text-slate-700" key={s}>{s}</span>)}</div></Card></div></>}
export function MyAppointments(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="My Appointments" text="Track appointment status, payment, and consultation details."/><AppointmentTable data={appts}/></>}
export function Prescriptions(){return <><PageHeader title="Prescriptions" text="View and download doctor prescriptions."/><div className="grid gap-5">{prescriptions.map(p=><Card className="p-6" key={p.id}><div className="flex flex-col justify-between gap-4 md:flex-row"><div><h3 className="text-xl font-black">{p.diagnosis}</h3><p className="text-slate-500">{p.doctorName} • {p.date}</p></div><button className="btn-secondary"><Download size={18}/>Download PDF</button></div><div className="mt-5 grid gap-3 md:grid-cols-2">{p.medicines.map(m=><div className="rounded-2xl bg-slate-50 p-4 dark:bg-slate-800" key={m.name}><p className="font-black">{m.name}</p><p className="text-sm text-slate-500">{m.dosage} • {m.frequency} • {m.duration}</p><p className="text-sm text-slate-500">{m.instruction}</p></div>)}</div></Card>)}</div></>}
export function Records(){return <><PageHeader title="Medical Records" text="Upload, view, and download medical reports." action={<button onClick={()=>toast.success("Upload simulated")} className="btn-primary"><Upload size={18}/>Upload Record</button>}/><RecordsList/></>}
export function Favorites(){return <><PageHeader title="Favorite Doctors" text="Saved doctors for faster appointments."/><div className="grid gap-5 md:grid-cols-3">{doctors.slice(0,3).map(d=><Card className="p-5" key={d.id}><img className="h-40 w-full rounded-3xl object-cover" src={d.image}/><h3 className="mt-4 font-black">{d.name}</h3><p className="text-slate-500">{d.specialization}</p><Link className="btn-primary mt-4 w-full" to={`/doctors/${d.id}`}>View Profile</Link></Card>)}</div></>}
export function Payments(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Payments" text="Consultation fee payments and payment statuses."/><AppointmentTable data={appts}/></>}
export function Notifications(){const {notifications,markNotificationRead}=useAppStore(); return <><PageHeader title="Notifications" text="Appointment reminders, prescription updates, and payment alerts."/><div className="space-y-4">{notifications.map(n=><Card className="p-5" key={n.id}><div className="flex justify-between gap-4"><div><p className="font-black">{n.title}</p><p className="text-slate-500">{n.message}</p><p className="mt-2 text-xs text-slate-400">{n.createdAt}</p></div>{!n.read && <button onClick={()=>markNotificationRead(n.id)} className="btn-secondary px-3 py-2">Mark read</button>}</div></Card>)}</div></>}
export function Settings(){return <><PageHeader title="Settings" text="Profile, notifications, privacy, medical info, and account preferences."/><Card className="p-6"><div className="grid gap-4 md:grid-cols-2"><input className="input" defaultValue="Nasir Uddin Khan"/><input className="input" defaultValue="patient@medicare.com"/><input className="input" defaultValue="+8801711111111"/><input className="input" defaultValue="Blood group: B+"/><select className="input"><option>Email notifications enabled</option><option>SMS reminders enabled</option></select><select className="input"><option>Privacy: Standard</option><option>Privacy: Strict</option></select></div><button className="btn-primary mt-5">Save Settings</button></Card></>}

export function DoctorDashboard(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Doctor Dashboard" text="Manage today's appointments, patients, prescriptions, schedule, and reviews."/><div className="grid gap-5 md:grid-cols-6"><StatCard label="Today" value="6" icon={<CalendarDays/>}/><StatCard label="Pending" value={String(appts.filter(a=>a.status==="Pending").length)} icon={<Clock/>}/><StatCard label="Completed" value="32" icon={<CheckCircle2/>}/><StatCard label="Patients" value="148" icon={<Users/>}/><StatCard label="Rating" value="4.9" icon={<Star/>}/><StatCard label="Earnings" value="$2.8k" icon={<DollarSign/>}/></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><AppointmentList title="Today's schedule" data={appts}/><LearningChart title="Monthly consultations"/></div></>}
export function DoctorAppointments(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Doctor Appointments" text="Confirm, complete, cancel, or reschedule appointments."/><AppointmentTable data={appts} doctorActions/></>}
export function DoctorCalendar(){return <><PageHeader title="Appointment Calendar" text="Monthly, weekly, and daily schedule UI."/><CalendarView/></>}
export function PatientList(){return <><PageHeader title="Patients" text="Patient list, appointment history, and medical summary."/><PatientsTable/></>}
export function PrescriptionWriter(){return <><PageHeader title="Prescription Writer" text="Create prescriptions with medicines, tests, notes, and follow-up."/><Card className="p-6"><div className="grid gap-4 md:grid-cols-2"><input className="input" defaultValue="Nasir Uddin Khan"/><input className="input" defaultValue="Hypertension follow-up"/><input className="input" placeholder="Medicine name" defaultValue="Amlodipine 5mg"/><input className="input" placeholder="Dosage" defaultValue="1 tablet daily"/><input className="input" placeholder="Duration" defaultValue="30 days"/><input className="input" placeholder="Follow-up date" type="date"/></div><textarea className="input mt-4 h-32" placeholder="Doctor note"/><button onClick={()=>toast.success("Prescription saved")} className="btn-primary mt-5">Save Prescription</button></Card></>}
export function ScheduleManagement(){return <><PageHeader title="Schedule Management" text="Availability, consultation fee, days, and time slots."/><Card className="p-6"><div className="grid gap-4 md:grid-cols-3"><input className="input" defaultValue="Monday - Thursday"/><input className="input" defaultValue="09:00 AM - 05:00 PM"/><input className="input" defaultValue="$45"/></div><button className="btn-primary mt-5">Update Schedule</button></Card></>}
export function DoctorReviews(){return <><PageHeader title="Reviews" text="Patient ratings and review replies."/><div className="space-y-4">{reviews.map(r=><Card className="p-5" key={r.text}><p className="font-black">{r.name}</p><p className="text-amber-500">★★★★★</p><p className="text-slate-500">{r.text}</p><button className="mt-3 font-bold text-brand-600">Reply</button></Card>)}</div></>}

export function AdminDashboard(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Admin Dashboard" text="Manage doctors, patients, appointments, payments, records, and platform analytics."/><div className="grid gap-5 md:grid-cols-4"><StatCard label="Patients" value="1,248" icon={<Users/>}/><StatCard label="Doctors" value="75" icon={<Stethoscope/>}/><StatCard label="Appointments" value={String(appts.length)} icon={<CalendarDays/>}/><StatCard label="Revenue" value="$42k" icon={<DollarSign/>}/></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><LearningChart title="Appointments and revenue"/><DepartmentPie/></div></>}
export function AdminDoctors(){return <><PageHeader title="Doctors Management" text="Add, approve, activate, edit, and manage doctor schedules." action={<button className="btn-primary"><Plus/>Add Doctor</button>}/><DoctorsTable/></>}
export function AdminPatients(){return <><PageHeader title="Patients Management" text="Search patients, view history, records, and payments."/><PatientsTable/></>}
export function AdminAppointments(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Appointments Management" text="Filter, update, and review appointment details."/><AppointmentTable data={appts} doctorActions/></>}
export function AdminDepartments(){return <><PageHeader title="Departments" text="Manage departments and specialist categories."/><div className="grid gap-5 md:grid-cols-4">{departments.map(d=><Card className="p-5" key={d.name}><HeartPulse className="text-brand-600"/><h3 className="mt-3 font-black">{d.name}</h3><p className="text-sm text-slate-500">{d.count} doctors</p></Card>)}</div></>}
export function AdminPayments(){const appts=useAppStore(s=>s.appointments); return <><PageHeader title="Payments" text="Payment status, refunds, fee tracking, and payment records."/><AppointmentTable data={appts}/></>}
export function AdminReports(){return <><PageHeader title="Reports" text="Appointment, revenue, department, doctor performance, and patient growth reports."/><div className="grid gap-6 lg:grid-cols-2"><LearningChart title="Monthly revenue"/><DepartmentPie/><Card className="p-6 lg:col-span-2"><button className="btn-secondary mr-3">Export CSV</button><button className="btn-secondary">Export PDF</button></Card></div></>}
export function AdminSettings(){return <><PageHeader title="Platform Settings" text="Hospital info, appointment rules, payment settings, notifications, and permissions."/><Card className="p-6"><div className="grid gap-4 md:grid-cols-2"><input className="input" defaultValue="MediCare Connect"/><input className="input" defaultValue="support@medicare.com"/><input className="input" defaultValue="Default slot duration: 30 min"/><input className="input" defaultValue="Platform fee: $3"/></div><button className="btn-primary mt-5">Save Settings</button></Card></>}

function AppointmentList({title,data}:{title:string;data:Appointment[]}){return <Card className="p-6"><h2 className="text-xl font-black">{title}</h2><div className="mt-4 space-y-3">{data.map(a=><div className="rounded-2xl border border-slate-200 p-4 dark:border-slate-800" key={a.id}><div className="flex justify-between"><div><p className="font-black">{a.doctorName}</p><p className="text-sm text-slate-500">{a.date} • {a.time} • {a.type}</p></div><StatusBadge status={a.status}/></div></div>)}</div></Card>}
function AppointmentTable({data,doctorActions=false}:{data:Appointment[];doctorActions?:boolean}){const update=useAppStore(s=>s.updateAppointmentStatus); return <Card className="overflow-hidden"><div className="overflow-x-auto"><table className="w-full"><thead><tr><th className="table-th">ID</th><th className="table-th">Patient</th><th className="table-th">Doctor</th><th className="table-th">Date</th><th className="table-th">Status</th><th className="table-th">Payment</th>{doctorActions&&<th className="table-th">Actions</th>}</tr></thead><tbody>{data.map(a=><tr className="border-t border-slate-100 dark:border-slate-800" key={a.id}><td className="table-td font-bold">{a.id}</td><td className="table-td">{a.patientName}</td><td className="table-td">{a.doctorName}</td><td className="table-td">{a.date} {a.time}</td><td className="table-td"><StatusBadge status={a.status}/></td><td className="table-td"><StatusBadge status={a.paymentStatus}/></td>{doctorActions&&<td className="table-td"><select className="input py-2" value={a.status} onChange={e=>update(a.id,e.target.value as any)}><option>Pending</option><option>Confirmed</option><option>Checked In</option><option>Completed</option><option>Cancelled</option><option>Rescheduled</option></select></td>}</tr>)}</tbody></table></div></Card>}
function RecordsList(){return <div className="grid gap-5 md:grid-cols-3">{records.map(r=><Card className="p-5" key={r.id}><FileText className="text-brand-600"/><h3 className="mt-3 font-black">{r.fileName}</h3><p className="text-sm text-slate-500">{r.type} • {r.department}</p><p className="mt-2 text-xs text-slate-400">{r.uploadedAt} • {r.size}</p><button className="btn-secondary mt-4 w-full"><Download size={18}/>Download</button></Card>)}</div>}
function PatientsTable(){const names=["Nasir Uddin Khan","Mira Hassan","Ravi Kumar","Sadia Islam","John Smith"]; return <Card className="overflow-hidden"><table className="w-full"><thead><tr><th className="table-th">Name</th><th className="table-th">Email</th><th className="table-th">Phone</th><th className="table-th">Blood</th><th className="table-th">Status</th></tr></thead><tbody>{names.map((n,i)=><tr className="border-t border-slate-100 dark:border-slate-800" key={n}><td className="table-td font-bold">{n}</td><td className="table-td">{n.toLowerCase().split(" ")[0]}@example.com</td><td className="table-td">+88017{i}000000</td><td className="table-td">{["B+","A+","O+","AB+"][i%4]}</td><td className="table-td"><StatusBadge status="Confirmed"/></td></tr>)}</tbody></table></Card>}
function DoctorsTable(){return <Card className="overflow-hidden"><table className="w-full"><thead><tr><th className="table-th">Doctor</th><th className="table-th">Department</th><th className="table-th">Fee</th><th className="table-th">Rating</th><th className="table-th">Status</th></tr></thead><tbody>{doctors.map(d=><tr className="border-t border-slate-100 dark:border-slate-800" key={d.id}><td className="table-td font-bold">{d.name}</td><td className="table-td">{d.department}</td><td className="table-td">${d.fee}</td><td className="table-td">{d.rating}</td><td className="table-td"><StatusBadge status={d.availableToday?"Confirmed":"Pending"}/></td></tr>)}</tbody></table></Card>}
function LearningChart({title}:{title:string}){return <Card className="p-6"><h2 className="mb-4 text-xl font-black">{title}</h2><ResponsiveContainer width="100%" height={280}><AreaChart data={analytics}><defs><linearGradient id="c" x1="0" y1="0" x2="0" y2="1"><stop offset="5%" stopColor="#06b6d4" stopOpacity={0.5}/><stop offset="95%" stopColor="#06b6d4" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" opacity={0.2}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Area type="monotone" dataKey="appointments" stroke="#06b6d4" fill="url(#c)"/></AreaChart></ResponsiveContainer></Card>}
function DepartmentPie(){const data=departments.slice(0,5).map(d=>({name:d.name,value:d.count})); const colors=["#06b6d4","#14b8a6","#3b82f6","#8b5cf6","#f59e0b"]; return <Card className="p-6"><h2 className="mb-4 text-xl font-black">Department-wise appointments</h2><ResponsiveContainer width="100%" height={280}><PieChart><Pie data={data} outerRadius={95} dataKey="value" label>{data.map((_,i)=><Cell key={i} fill={colors[i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></Card>}
function CalendarView(){return <Card className="p-6"><div className="grid grid-cols-7 gap-2">{Array.from({length:35}).map((_,i)=><div key={i} className={`min-h-24 rounded-2xl border border-slate-200 p-2 dark:border-slate-800 ${[5,12,20].includes(i)?"bg-brand-50 dark:bg-brand-950":""}`}><p className="text-sm font-bold">{i+1}</p>{[5,12,20].includes(i)&&<p className="mt-2 rounded-lg bg-brand-600 p-1 text-xs text-white">Appointment</p>}</div>)}</div></Card>}
